name: punch

on:
  push:
    branches:
    - main
  schedule:
  - cron: "05 22 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: SetUp
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Punch
      env:
        IDCARD: ${{ secrets.idcard }}
      run: go run main.go $IDCARD
